### ISSUE TITLE
[Bug] Display video feed in browser

### ISSUE THREAD

**Issue by samiamlabs** [eclipse-zenoh/zenoh-plugin-webserver#211]
### Describe the bug

I'm having som issues with displaying a video stream like in the example from: https://github.com/eclipse-zenoh/zenoh-demos/tree/master/ROS2/zenoh-rest-teleop

If I use <`img src="my-site/demo/zcam"></img>` I get a static image just fine, but with  ` <img src="my-site/demo/zcam?_method=SUB"></img>` I get the following error from zenohd:

```bash
thread 'async-std/runtime' panicked at src/lib.rs:167:17:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```

And the following in the browser:

```
Failed to load resource: net::ERR_EMPTY_RESPONSE
```

It is quite possible that I misunderstood something about the required setup, and that this is not a bug.

### To reproduce

1. Start zenohd with the following config:
```
{
  plugins: {
    webserver: {
      http_port: 8080,
    },
    storage_manager: {
      volumes: {
        fs: {}
      },
      storages: {
        demo: {
          key_expr: "my-site/**",
          strip_prefix: "my-site",
          volume: {
            id: "fs",
            dir: "my-site",
            read_only: false
          }
        }
      }
    }
  }
}
```
2. Start zcapture.py, slightly modified for v.1.0.0
3. Make an index.html under ~/.zenoh/zenoh_backend_fs/my-site and add:
`<img src="http://localhost:8080/my-site/demo/zcam?_method=SUB"></img>`
5. Open http://localhost:8080/my-site/ in a browser.
6. See errors.

### System info

- Platform: macOS aarach64
- Zenoh version: v1.0.0

**Comment by gabrik** [comment]
Hi @samiamlabs, thank you for reporting, it seems coming from this line: https://github.com/eclipse-zenoh/zenoh-plugin-webserver/blob/main/src/lib.rs#L167

We are going to schedule a fix.
